import assert from "node:assert/strict";
import fs from "node:fs";

const css = fs.readFileSync(new URL("../styles/tormenta20-ficha-heroica.css", import.meta.url), "utf8");
const journal = fs.readFileSync(new URL("../templates/vendor/tormenta20-1.5.015/journal.hbs", import.meta.url), "utf8");
const characterSheet = fs.readFileSync(new URL("../templates/character-sheet.hbs", import.meta.url), "utf8");
const favorites = fs.readFileSync(new URL("../templates/vendor/tormenta20-1.5.015/lists/list-favorites.hbs", import.meta.url), "utf8");
const script = fs.readFileSync(new URL("../scripts/tormenta20-ficha-heroica.mjs", import.meta.url), "utf8");
const preview = fs.readFileSync(new URL("../preview/index.html", import.meta.url), "utf8");
const previewCss = fs.readFileSync(new URL("../preview/preview-base.css", import.meta.url), "utf8");
const campaignConfig = fs.readFileSync(new URL("../templates/campaign-identity-config.hbs", import.meta.url), "utf8");
const manifest = JSON.parse(fs.readFileSync(new URL("../module.json", import.meta.url), "utf8"));

assert.match(css, /nav\.sheet-tabs\s*\{[^}]*justify-content:\s*center;/s, "the category bar is centered");
assert.match(css, /nav\.sheet-tabs\s*\{[^}]*flex-wrap:\s*nowrap;/s, "category buttons remain on one row");
assert.match(css, /nav\.sheet-tabs \.item\s*\{[^}]*flex:\s*0 1 160px;/s, "category buttons form a centered group");
assert.match(css, /\.t20ga-window\s*\{[^}]*min-width:\s*620px;[^}]*min-height:\s*560px;/s, "the sheet can be resized to a compact usable window");
assert.match(css, /\.window-resizable-handle,[\s\S]*\.window-resize-handle\s*\{[^}]*z-index:\s*2147483647;[^}]*pointer-events:\s*auto;/s, "Foundry resize handles stay interactive above the custom sheet");
assert.match(css, /@container \(max-width: 900px\)[\s\S]*grid-template-rows:\s*clamp\(190px, 30%, 240px\) minmax\(0, 1fr\);/s, "medium sheets move the artwork into a compact horizontal header");
assert.match(css, /@container \(max-width: 900px\)[\s\S]*\.t20ga-dashboard\.active\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\);/s, "dense dashboard panels stack when the sheet narrows");
assert.match(css, /@container \(max-width: 720px\)[\s\S]*nav\.sheet-tabs\s*\{[^}]*overflow-x:\s*auto;/s, "all category tabs remain reachable in the narrow layout");
assert.equal((journal.match(/class="t20ga-journal-expand"/g) ?? []).length, 6, "every character journal card has an expand button");
assert.match(css, /article\.is-expanded\s*\{[^}]*position:\s*absolute !important;[^}]*inset:\s*0 !important;/s, "expanded journal cards occupy the panel");
assert.match(css, /article\.is-expanded > \*:not\(\.section-titles\)\s*\{[^}]*flex:\s*1 1 0 !important;[^}]*height:\s*auto !important;/s, "expanded journal editor roots grow with the card");
assert.match(css, /article\.is-expanded \.editor-container\s*\{[^}]*display:\s*flex !important;[^}]*flex-direction:\s*column !important;/s, "Foundry editor containers can use the expanded height");
assert.match(css, /\.t20ga-hero-art\s*\{[^}]*width:\s*var\(--t20ga-art-fit-width, 100%\);[^}]*height:\s*var\(--t20ga-art-fit-height, 100%\);[^}]*object-fit:\s*contain;/s, "avatar and token art use calculated frame-filling dimensions");
assert.match(characterSheet, /class="t20ga-hero-art-backdrop"/, "the hero frame has a full-bleed backdrop");
assert.match(css, /\.t20ga-hero-art-backdrop\s*\{[^}]*object-fit:\s*cover;[^}]*filter:\s*blur\(12px\)[^;]*brightness\(0\.52\);/s, "the backdrop fills the frame without cropping the foreground art");
assert.match(script, /DEFAULT_ART_POSITION = Object\.freeze\(\{ x: 0, y: 0, scale: 1 \}\)/, "art adjustment keeps the original scale and position controls");
assert.match(script, /const coverScale = Math\.max\(stageWidth \/ imageWidth, stageHeight \/ imageHeight\);/, "the default 1x scale automatically fills the frame");
assert.match(script, /--t20ga-art-fit-width/, "the calculated cover size is applied without pre-cropping the image element");
assert.match(script, /name="scale" min="0\.25" max="1\.8"/, "the slider can zoom out enough to reveal wide artwork");
assert.doesNotMatch(script, /name="fit"/, "the art dialog does not expose a cropping mode");
assert.match(css, /\.t20ga-dialog-art\s*\{[^}]*object-fit:\s*contain;/s, "the adjustment preview always shows the complete image");
assert.match(script, /class="t20ga-dialog-art-backdrop"/, "the adjustment preview shows the same filled-frame treatment");
assert.match(script, /if \(heroArtBackdrop\) heroArtBackdrop\.src = src;/, "the backdrop follows avatar and token changes");
assert.match(css, /#context-menu \.context-item[^}]*color:\s*#fff7e4 !important;/s, "context menu labels remain readable on the dark menu");
assert.doesNotMatch(characterSheet, /t20ga-party-rail/, "the unused lower gallery is absent from the sheet");
assert.doesNotMatch(script, /partyGallery|galleryCollapsed|PARTY_ART/, "gallery settings and behavior are removed");
assert.match(characterSheet, /class="t20ga-campaign-logo"/, "a configured campaign logo is rendered");
assert.match(characterSheet, /class="t20ga-brand-placeholder"/, "an image-free campaign logo placeholder is available");
assert.doesNotMatch(characterSheet, /class="t20ga-brand-title"/, "the old fixed sheet title is absent");
assert.match(characterSheet, /class="t20ga-hero-sigil"/, "the hero panel uses a CSS-native geometric seal");
assert.match(characterSheet, /class="t20ga-switch-thumb"/, "the art switch uses a CSS-native marker");
assert.doesNotMatch(characterSheet, /t20ga\.(?:logo|eye)/, "removed branding assets are not referenced by the sheet");
assert.doesNotMatch(script, /tormenta20-logo|olho-tormenta/, "removed branding assets are not exposed by the sheet data");
assert.doesNotMatch(css, /assets\/branding/, "the stylesheet does not load removed branding assets");
assert.doesNotMatch(preview, /tormenta20-logo|olho-tormenta|assets\/branding/, "the preview does not expose removed branding assets");
assert.doesNotMatch(preview, /assets\/party/, "the preview does not load bundled character artwork");
assert.match(previewCss, /\.t20ga-preview-portrait/, "the preview uses a CSS-native portrait placeholder");
assert.doesNotMatch(script, /assets\/party/, "the runtime does not load bundled character artwork");
assert.match(script, /scope: "world"[\s\S]*default: DEFAULT_CAMPAIGN_IDENTITY/, "campaign identity is stored in the world");
assert.match(script, /restricted: true/, "only game masters can open campaign identity settings");
assert.match(script, /PERSONAL_APPEARANCE_FLAG = "personalAppearanceByActor"/, "personal themes are stored on the user document");
assert.match(script, /\[actorAppearanceKey\(actor\)\]: normalizePersonalAppearance\(appearance\)/, "personal themes are saved separately by actor");
assert.match(script, /name="frame"/, "the logo dialog includes personal frame styles");
assert.match(script, /name="layout"/, "the logo dialog includes a tabbed or continuous layout choice");
assert.match(script, /name="background"/, "the logo dialog includes personal sheet backgrounds");
assert.match(script, /name="backgroundImage"/, "the logo dialog accepts a personal background image");
assert.match(script, /t20ga-background-file-picker/, "the personal background uses the Foundry image picker");
assert.match(script, /dataset\.t20gaFrame = appearance\.frame/, "the selected frame style reaches the sheet window");
assert.match(script, /dataset\.t20gaLayout = appearance\.layout/, "the selected layout reaches the sheet window");
assert.match(script, /sections\.addClass\("active"\)/, "continuous mode activates every Foundry tab section");
assert.match(script, /sections\.removeClass\("active"\)/, "returning to tabs restores a single active section");
assert.match(script, /dataset\.t20gaBackground = appearance\.background/, "the selected background reaches the sheet window");
assert.match(css, /\[data-t20ga-background="custom"\] \.window-content\s*\{[^}]*--t20ga-custom-background/s, "custom background images cover the sheet behind a readable overlay");
assert.match(css, /\[data-t20ga-frame="arcane"\] \.t20ga-hero-frame/, "the arcane frame style is available");
assert.match(css, /\[data-t20ga-frame="forged"\] \.t20ga-hero-frame/, "the forged frame style is available");
assert.match(css, /\[data-t20ga-frame="minimal"\] \.t20ga-hero-frame/, "the minimal frame style is available");
assert.match(css, /\[data-t20ga-layout="continuous"\] nav\.sheet-tabs\s*\{[^}]*display:\s*none;/s, "continuous mode removes the tab bar");
assert.match(css, /\[data-t20ga-layout="continuous"\] \.t20ga-sheet-body > \.tab\s*\{[^}]*display:\s*block !important;/s, "continuous mode makes every sheet section visible");
assert.match(characterSheet, /class="t20ga-continuous-heading"/, "continuous sections have visible headings");
assert.match(campaignConfig, /name="logo"/, "campaign identity includes a logo selector");
assert.match(campaignConfig, /name="logoScale" min="0\.5" max="1\.8"/, "campaign identity includes a fluid logo scale control");
assert.match(campaignConfig, /name="logoPositionX" min="-60" max="60"/, "campaign identity includes horizontal logo positioning");
assert.match(campaignConfig, /name="logoPositionY" min="-40" max="40"/, "campaign identity includes vertical logo positioning");
assert.match(characterSheet, /--t20ga-campaign-logo-scale: \{\{t20ga\.campaignLogoScale\}\}/, "the saved logo scale reaches the character sheet");
assert.match(css, /grid-template-columns:\s*minmax\(245px, var\(--t20ga-hero-panel-width, 25%\)\)/, "the surrounding sheet layout follows the logo width");
assert.match(css, /\.t20ga-campaign-logo\s*\{[^}]*height:\s*calc\(64px \* var\(--t20ga-campaign-logo-scale, 1\)\);[^}]*max-height:\s*none;/s, "the logo grows through layout instead of a cropped transform");
assert.doesNotMatch(css, /\.t20ga-campaign-logo\s*\{[^}]*transform:/s, "the campaign logo is never enlarged outside a fixed clipping frame");
assert.match(campaignConfig, /name="title"/, "campaign identity includes an optional title");
assert.match(campaignConfig, /name="groupName"/, "campaign identity includes an optional group name");
assert.match(script, /"t20ga\.list-favorites":/, "the isolated favorites template is registered");
assert.match(script, /favorites\.poderes\?\.length/, "favorite powers make the card visible");
assert.match(script, /Number\(favorites\.qtdMagias\) > 0/, "favorite spells make the card visible");
assert.match(characterSheet, /class="t20ga-card t20ga-favorites-card"/, "the first tab includes a favorites card");
assert.match(characterSheet, /\{\{> "t20ga\.list-favorites"\}\}/, "the first tab renders the isolated favorites partial");
assert.match(favorites, /actor\.favoritos\.poderes/, "favorite powers are rendered");
assert.match(favorites, /actor\.favoritos\.qtdMagias/, "favorite spells are rendered");
assert.match(script, /journalExpandButtons\.on\("click"/, "journal expand buttons are interactive");
assert.match(script, /\.\.\.\(baseOptions\.scrollY \?\? \[\]\)/, "the heroic sheet retains the system scroll containers");
assert.match(script, /"\.skills-list"/, "skill list scroll is preserved across actor updates");
assert.match(script, /"\.t20ga-dashboard-side"/, "dashboard side panel scroll is preserved across actor updates");
assert.match(script, /"\.t20ga-sheet-body > \.tab"/, "active tab scroll is preserved across actor updates");
assert.equal(manifest.version, "1.6.23", "manifest version is updated");
assert.equal(manifest.compatibility.verified, "14.367", "Foundry 14 compatibility is declared");
assert.equal(manifest.relationships.systems[0].compatibility.verified, "1.6.1", "Tormenta20 1.6.1 compatibility is declared");
assert.equal(
  manifest.manifest,
  "https://github.com/CalisteniaStudios/tormenta20-ficha-heroica/releases/latest/download/module.json",
  "manifest updates avoid the raw GitHub endpoint"
);

console.log("Ficha Heroica UI regression checks passed");
